### ISSUE TITLE
Common Button and its variants implementation

### ISSUE THREAD

**Issue by borabiricik** [BursaBilisimToplulugu/maps#2]
Go to: [Figma File](https://www.figma.com/file/wUVD6IfnxiYYtah7PB8Sai/noName?type=design&node-id=45%3A6819&mode=dev)

Navigate "Style Guide" from top-left panel (or follow [this link)](https://www.figma.com/file/wUVD6IfnxiYYtah7PB8Sai/noName?type=design&node-id=45-6691&mode=dev)

1-) Create file "src/app/common/Button/variants/{YourButtonVariant}.tsx"
2-) Create your Button variant (Text, Primary, etc.)
3-) Create your Button's Story in StoryBook (You can reffer src/stories/Button.stories.tsx)
4-) Make sure your button works

## Feel free to contact us

**Comment by Demir-Utku** [comment]
Trello'da bu task bana atandi, burada da atanabilir.
