### ISSUE TITLE
Common Scrollbar component implementation #11

### ISSUE THREAD

**Issue by YagmurrrCan** [BursaBilisimToplulugu/maps#22]
Go to: [Figma File](https://www.figma.com/file/wUVD6IfnxiYYtah7PB8Sai/noName?type=design&node-id=45%3A6819&mode=dev)

Navigate "Style Guide" from top-left panel (or follow [this link)](https://www.figma.com/file/wUVD6IfnxiYYtah7PB8Sai/noName?type=design&node-id=45-39757&mode=dev)

1-) Create file "src/app/common/Scrollbar/index.tsx"
2-) Create your Scrollbar
3-) Create your Scrollbar Story in StoryBook (You can reffer src/stories/Button.stories.tsx)
4-) Make sure your Scrollbar works

**Comment by Demir-Utku** [comment]
Taski alabilirim

**Comment by Demir-Utku** [comment]
@borabiricik scrollbar icin wrapper component mi yazayim, icinde children prop'u olan, yoksa scrollbar'i her yerde ayni stillerle kullanabilmek icin stiller mi ekleyeyim? 

Wrapper yazarsak scroll olan her yerde bu component'i kullanmak gerekecek, bunun gibi:

```tsx
return (
  <ScrollBar ...>
    ...
  </ScrollBar>
)
```

**Comment by borabiricik** [comment]
Selamlar @Demir-Utku ,
Wrapper seklinde degil de tum scrollbarlari global olarak override edelim.

**Comment by Demir-Utku** [comment]
selamlar @borabiricik,
tamamdir, yani component olarak yazilacak bir sey yok o zaman, sadece global styling olacak gibi. Ayni sekilde storybook dosyasina da gerek yok gibi

**Comment by borabiricik** [comment]
Evet globals.css e yaptığımız zaman yeterlidir

**Comment by Demir-Utku** [comment]
Tasarimda scrollbar'in oldugu yer pagination'in altinda mi?

<img width="610" alt="Screenshot 2023-11-14 at 00 24 41" src="https://github.com/BursaBilisimToplulugu/maps/assets/50655392/83e0e330-cf1c-4324-ad22-3e06b80610cf">

<br />

Eger oysa, genisligi cok az, 4px gozukmuyor neredeyse. Asagidaki gibi oldu:

<img width="1728" alt="Screenshot 2023-11-14 at 00 23 31" src="https://github.com/BursaBilisimToplulugu/maps/assets/50655392/0c1da564-19f6-4c97-a0ec-9cdc7713d504">
