### ISSUE TITLE
Common Divider implementation

### ISSUE THREAD

**Issue by borabiricik** [BursaBilisimToplulugu/maps#5]
Go to: [Figma File](https://www.figma.com/file/wUVD6IfnxiYYtah7PB8Sai/noName?type=design&node-id=45%3A6819&mode=dev)

Navigate "Style Guide" from top-left panel (or follow [this link)](https://www.figma.com/file/wUVD6IfnxiYYtah7PB8Sai/noName?type=design&node-id=45-39757&mode=dev)

1-) Create file "src/app/common/Divider/index.tsx"
2-) Create your Divider
3-) Create your Divider's Story in StoryBook (You can reffer src/stories/Button.stories.tsx)
4-) Make sure your Divider works

## Feel free to contact us

**Comment by yasin03** [comment]
May I take this task ?
