### ISSUE TITLE
Common Item Card component implementation

### ISSUE THREAD

**Issue by borabiricik** [BursaBilisimToplulugu/maps#9]
Go to: [Figma File](https://www.figma.com/file/wUVD6IfnxiYYtah7PB8Sai/noName?type=design&node-id=45%3A6819&mode=dev)

Navigate "Style Guide" from top-left panel (or follow [this link)](https://www.figma.com/file/wUVD6IfnxiYYtah7PB8Sai/noName?type=design&node-id=45-39757&mode=dev)

1-) Create file "src/app/common/ItemCard/index.tsx"
2-) Create your ItemCard
3-) Create your ItemCard Story in StoryBook (You can reffer src/stories/Button.stories.tsx)
4-) Make sure your ItemCard works (should receive rating from props)

## Feel free to contact us

**Comment by atalay02** [comment]
Ben alabilir miyim
